# Generated by Django 4.2.20 on 2025-04-01 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythonscripttask',
            name='script',
            field=models.TextField(help_text='请输入要执行的Python代码，目前只支持python3.8版本的，注意：\n1. result: 用于存储需要发送给用户消息，一定要设置为脚本的全局变量，且是字符串类型\n2. 请自行确保docker环境已经按照了模块，可以联系管理员添加requirements.txt\n3. result 为空字符串时，不发送消息\n', verbose_name='Python脚本代码'),
        ),
        migrations.AlterField(
            model_name='pythonscripttask',
            name='timeout',
            field=models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(0)], verbose_name='超时时间(秒)'),
        ),
    ]
