# Generated by Django 4.2.20 on 2025-04-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_pythonscripttask_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonscripttask',
            name='is_run_now',
            field=models.BooleanField(default=False, help_text='如果为True，则创建和更新任务时立刻执行', verbose_name='是否立刻执行'),
        ),
    ]
