# Generated by Django 4.2.20 on 2025-04-01 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_pythonscripttask_is_run_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythonscripttask',
            name='frequency',
            field=models.FloatField(default=5, help_text='可以小数会折算成秒，一个小时输入：60，一天输入：1440', validators=[django.core.validators.MinValueValidator(0)], verbose_name='执行频率(分钟)'),
        ),
    ]
