# Generated by Django 2.2.13 on 2025-03-30 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_auto_20210203_1749'),
        ('task', '0008_auto_20210314_1924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='PageMonitorTask',
        ),
    ]
