# Generated by Django 2.2.13 on 2025-03-31 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_auto_20210203_1749'),
        ('task', '0009_auto_20250330_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonScriptTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('script', models.TextField(help_text='请输入要执行的Python代码，目前只支持python3.6版本的，注意：\n1. result: 用于存储需要发送给用户消息，一定要设置为脚本的全局变量，且是字符串类型\n2. 请自行确保docker环境已经按照了模块，可以联系管理员添加requirements.txt\n', verbose_name='Python脚本代码')),
                ('description', models.TextField(help_text='简单描述一下脚本任务，方便管理的时候知道这个任务是做什么的', verbose_name='脚本描述')),
                ('frequency', models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='执行频率(分钟)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('timeout', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(0)], verbose_name='超时时间(秒)')),
                ('no_repeat', models.BooleanField(default=True, help_text='如果为True，则只有在和上一次消息不一样的时候才发送', verbose_name='是否去重')),
                ('notification', models.ManyToManyField(to='setting.Notification', verbose_name='通知方式')),
            ],
            options={
                'verbose_name': 'Python脚本任务',
                'verbose_name_plural': 'Python脚本任务管理',
            },
        ),
    ]
