# Generated by Django 4.2.20 on 2025-04-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarkSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='https://api.day.app或者http://8.210.22.195:8080，请注意不要/结尾', max_length=100, verbose_name='Bark server url')),
            ],
            options={
                'verbose_name': 'Bark 设置',
                'verbose_name_plural': 'Bark 设置',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '日志查看',
                'verbose_name_plural': '日志查看',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='默认名称', max_length=32, unique=True, verbose_name='通知方式名称')),
                ('type', models.IntegerField(choices=[(0, '邮箱'), (1, '微信'), (2, 'pushover'), (3, 'Bark'), (4, '自定义通知'), (5, 'Slack'), (6, 'Telegram')], default='邮箱', verbose_name='通知方式类型')),
                ('content', models.CharField(max_length=512, verbose_name='邮箱地址 / Server 酱 SCKEY /             Pushover User Key / Bark key / 自定义网址 / Slack channel / Telegram chat_id')),
            ],
            options={
                'verbose_name': '通知方式',
                'verbose_name_plural': '通知方式',
            },
        ),
        migrations.CreateModel(
            name='PushoverSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.CharField(max_length=100, verbose_name='Pushover API Token')),
            ],
            options={
                'verbose_name': 'Pushover 设置',
                'verbose_name_plural': 'Pushover 设置',
            },
        ),
        migrations.CreateModel(
            name='SlackSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, verbose_name='Slack OAuth Access Token')),
            ],
            options={
                'verbose_name': 'Slack 设置',
                'verbose_name_plural': 'Slack 设置',
            },
        ),
        migrations.CreateModel(
            name='SystemMailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_server', models.CharField(default='localhost', max_length=32, verbose_name='邮箱服务器')),
                ('mail_port', models.IntegerField(default=25, verbose_name='端口')),
                ('mail_username', models.CharField(default='默认用户名', max_length=64, verbose_name='用户名')),
                ('mail_sender', models.CharField(default='默认用户名@mail.com', max_length=64, verbose_name='发件人')),
                ('mail_password', models.CharField(default='默认密码', max_length=64, verbose_name='密码')),
            ],
            options={
                'verbose_name': '系统邮箱',
                'verbose_name_plural': '系统邮箱',
            },
        ),
        migrations.CreateModel(
            name='TelegramSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, verbose_name='Telegram Bot Token')),
            ],
            options={
                'verbose_name': 'Telegram Bot 设置',
                'verbose_name_plural': 'Telegram Bot 设置',
            },
        ),
    ]
