# Generated by Django 2.2.13 on 2025-04-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_auto_20210203_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarkSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='https://api.day.app/或者http://8.210.22.195:8080/', max_length=100, verbose_name='Bark server url')),
            ],
            options={
                'verbose_name': 'Bark 设置',
                'verbose_name_plural': 'Bark 设置',
            },
        ),
    ]
