# Generated by Django 2.2.13 on 2025-04-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0007_barksetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barksetting',
            name='domain',
            field=models.CharField(help_text='https://api.day.app或者http://8.210.22.195:8080，请注意不要/结尾', max_length=100, verbose_name='Bark server url'),
        ),
    ]
